name: First Github Action Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name : Print Greeting
        run : echo "Hello World ðŸ’»"
      - name : Print Goodbye
        run : echo "GoodBye ðŸ‘‹"
      
